/*******************************************************************************
 * ICP - Dáma klient 2008:
 * -----------------------------------------------------------------------------
 *     Černý Lukáš          <xcerny37@stud.fit.vutbr.cz>
 *     Dvořák Miroslav      <xdvora11@stud.fit.vutbr.cz>
 *     Mrázek Petr          <xmraze03@stud.fit.vutbr.cz>
 *     Oujeský Miroslav     <xoujes00@stud.fit.vutbr.cz>
 ***************************************************************************//**
 * @file HelpWindow.h
 * 
 * Okno s nápovědou.
 * 
 * Obsahuje zobrazovač HTML který zobrazí soubor s nápovědou.
 *
 * @version $Rev: 149 $
 ******************************************************************************/

// -*- C++ -*- generated by wxGlade 0.6.3 on Sun Apr 20 23:10:55 2008

#include <wx/wx.h>
#include <wx/image.h>
#include <wx/html/htmlwin.h>

#ifndef HELPWINDOW_H
#define HELPWINDOW_H

// begin wxGlade: ::dependencies
// end wxGlade

// begin wxGlade: ::extracode

// end wxGlade


class HelpWindow: public wxFrame {
public:
    // begin wxGlade: HelpWindow::ids
    // end wxGlade

    HelpWindow(wxWindow* parent, int id, const wxString& title, const wxPoint& pos=wxDefaultPosition, const wxSize& size=wxDefaultSize, long style=wxDEFAULT_FRAME_STYLE);

private:
    // begin wxGlade: HelpWindow::methods
    void set_properties();
    void do_layout();
    // end wxGlade

protected:
    // begin wxGlade: HelpWindow::attributes
    wxHtmlWindow* htmlWindow;
    // end wxGlade
}; // wxGlade: end class


#endif // HELPWINDOW_H
