/*******************************************************************************
 * ICP - Dáma klient 2008:
 * -----------------------------------------------------------------------------
 *     Černý Lukáš          <xcerny37@stud.fit.vutbr.cz>
 *     Dvořák Miroslav      <xdvora11@stud.fit.vutbr.cz>
 *     Mrázek Petr          <xmraze03@stud.fit.vutbr.cz>
 *     Oujeský Miroslav     <xoujes00@stud.fit.vutbr.cz>
 ***************************************************************************//**
 * @file LoginWindow.h
 * 
 * Okno pro přihlašování.
 * 
 * Obsahuje pole pro adresu serveru, uživatelské jméno a heslo. Adresa serveru 
 * a uživatelské jméno se ukládá do konfiguračního souboru, aby se nemuselo 
 * opětovně vyplňovat.
 * 
 * Z tohoto okna je přímo možné registrovat na serveru nového uživatele.
 *
 * @version $Rev: 160 $
 ******************************************************************************/

// -*- C++ -*- generated by wxGlade 0.6.3 on Wed Apr 16 18:38:49 2008

#include <wx/wx.h>
#include <wx/image.h>
#include "client_connect.h"
#include "ticpp.h"
#include <iostream>
#include "cl_receiver.h"

#ifndef LOGINWINDOW_H
#define LOGINWINDOW_H

class LoginWindow: public wxFrame, public Receiver
{
public:
    // begin wxGlade: LoginWindow::ids
    // end wxGlade

    LoginWindow(wxWindow* parent, int id, const wxString& title, const wxPoint& pos=wxDefaultPosition, const wxSize& size=wxDefaultSize, long style=wxDEFAULT_FRAME_STYLE);
    
    /// metoda pro příjem zpráv ze sítě, vrací true při zpracování zprávy, false když se zprávu zpracovat nepodaří
    virtual int Receive(std::string zprava);

private:
    // begin wxGlade: LoginWindow::methods
    void set_properties();
    void do_layout();
    // end wxGlade
    
    /**
     * Vraci true, pokud je vše správně vyplněno
     */
    bool isAllFilled();
    
    /**
     * V této proměnné je uloženo, zda po zavření tohoto okna povolit přihlašování
     */
    bool haveToEnableLogin;

protected:
    // begin wxGlade: LoginWindow::attributes
    wxStaticText* labelServer;
    wxTextCtrl* textServer;
    wxStaticText* labelUser;
    wxTextCtrl* textUser;
    wxStaticText* labelPassword;
    wxTextCtrl* textPassword;
    wxButton* buttonRegister;
    wxButton* buttonLogin;
    // end wxGlade
    
public:
    virtual void clickLogin(wxCommandEvent &event); // wxGlade: <event_handler>
    virtual void clickRegister(wxCommandEvent &event); 
    virtual void onCloseWindow(wxCloseEvent &event);
    //virtual void onSocketEvent(wxSocketEvent &event);
    
}; // wxGlade: end class



#endif // LOGINWINDOW_H
