/*******************************************************************************
 * ICP - Dáma klient 2008:
 * -----------------------------------------------------------------------------
 *     Černý Lukáš          <xcerny37@stud.fit.vutbr.cz>
 *     Dvořák Miroslav      <xdvora11@stud.fit.vutbr.cz>
 *     Mrázek Petr          <xmraze03@stud.fit.vutbr.cz>
 *     Oujeský Miroslav     <xoujes00@stud.fit.vutbr.cz>
 ***************************************************************************//**
 * @file MenuWindow.cpp
 *
 * Implementace okna s menu.
 *
 * @version $Rev: 173 $
 ******************************************************************************/

// -*- C++ -*- generated by wxGlade 0.6.3 on Wed Apr 16 18:38:49 2008

#include "MenuWindow.h"
#include "gameWindow.h"
#include "replayWindow.h"
#include "LoginWindow.h"
#include "HelpWindow.h"

#include <wx/aboutdlg.h>

// begin wxGlade: ::extracode

// end wxGlade


MenuWindow::MenuWindow(wxWindow* parent, int id, const wxString& title, const wxPoint& pos, const wxSize& size, long style):
    wxFrame(parent, id, title, pos, size, wxDEFAULT_FRAME_STYLE)
{
    // begin wxGlade: MenuWindow::MenuWindow    
    bitmapLogo = new wxStaticBitmap(this, wxID_ANY, wxBitmap(wxT("data/logo.png"), wxBITMAP_TYPE_ANY));
    buttonLogin = new wxButton(this, wxID_ANY, _("Přihlásit"));
    buttonLocal = new wxButton(this, wxID_ANY, _("Lokální hra"));
    buttonReplay = new wxButton(this, wxID_ANY, _("Přehrávání"));
    buttonHelp = new wxButton(this, wxID_ANY, _("Nápověda"));
    buttonQuit = new wxButton(this, wxID_ANY, _("Ukončit"));
    buttonAbout = new wxButton(this, wxID_ANY, _("O programu"));
    
    // napojení eventů na tlačítka
    Connect(buttonLogin->GetId(), wxEVT_COMMAND_BUTTON_CLICKED, wxCommandEventHandler(MenuWindow::clickLogin));
    Connect(buttonLocal->GetId(), wxEVT_COMMAND_BUTTON_CLICKED, wxCommandEventHandler(MenuWindow::clickLocal));
    Connect(buttonReplay->GetId(), wxEVT_COMMAND_BUTTON_CLICKED, wxCommandEventHandler(MenuWindow::clickReplay));
    Connect(buttonHelp->GetId(), wxEVT_COMMAND_BUTTON_CLICKED, wxCommandEventHandler(MenuWindow::clickHelp));
    Connect(buttonQuit->GetId(), wxEVT_COMMAND_BUTTON_CLICKED, wxCommandEventHandler(MenuWindow::clickQuit));
    Connect(buttonAbout->GetId(), wxEVT_COMMAND_BUTTON_CLICKED, wxCommandEventHandler(MenuWindow::clickAbout));

    set_properties();
    do_layout();
    // end wxGlade
}


BEGIN_EVENT_TABLE(MenuWindow, wxFrame)
    EVT_CLOSE(MenuWindow::onCloseWindow)
END_EVENT_TABLE();


/**
 * Event handler pro kliknutí na tlačítko pro login
 * @param event
 */
void MenuWindow::clickLogin(wxCommandEvent &event)
{
    disableLogin();
    
    LoginWindow* login = new LoginWindow(this, wxID_ANY, wxEmptyString);
    login->Show();
}

/**
 * Event handler pro kliknutí na tlačítko pro lokální hru
 * @param event
 */
void MenuWindow::clickLocal(wxCommandEvent &event)
{
//    gameWindow* localGame = new gameWindow(this, wxID_ANY, wxEmptyString);
	wxString a,b,c;
	a = _T("Černý");
	b = _T("Bílý");
	c = _T("Černý");
	std::string str = "";
	
    gameWindow* localGame = new gameWindow(this, wxID_ANY, wxEmptyString, false, a, b, c, str);
    localGame->Show();
}

/**
 * Event handler pro kliknutí na tlačítko pro přehrávání her
 * @param event
 */
void MenuWindow::clickReplay(wxCommandEvent &event)
{
    replayWindow* replay = new replayWindow(this, wxID_ANY, wxEmptyString);
    replay->Show();
}

/**
 * Event handler pro kliknutí na tlačítko pro nápovědu
 * @param event
 */
void MenuWindow::clickHelp(wxCommandEvent &event)
{
    //zavolá defaultní prohlížeč a zobrazí nápovědu ve formátu html.
    //wxLaunchDefaultBrowser(wxT("file:///home/smoliczech/Desktop/IPP/trunk/help/index.html"));
    HelpWindow* help = new HelpWindow(this, wxID_ANY, wxEmptyString);
    help->Show();
    
}

/**
 * Event handler pro kliknutí na tlačíko pro ukončení
 * @param event
 */
void MenuWindow::clickQuit(wxCommandEvent &event)
{
    // zavřeme toto okno (které by mělo být hlavním oknem aplikace)
    this->Close();
}

/**
 * Event handler pro kliknutí na tlačíko O programu
 * @param event
 */
void MenuWindow::clickAbout(wxCommandEvent &event)
{
    wxAboutDialogInfo info;
    info.SetName(_("Dáma 2008"));
    info.SetDescription(_("Černý Lukáš <xcerny37@stud.fit.vutbr.cz\n"
                          "Dvořák Miroslav <xdvora11@stud.fit.vutbr.cz>\n"
                          "Mrázek Petr <xmraze03@stud.fit.vutbr.cz>\n"
                          "Oujeský Miroslav <xoujes00@stud.fit.vutbr.cz>"));
    
    wxAboutBox(info);
}

/**
 * Event handler pro zavření okna (a tím pádem celé aplikace)
 * @param event
 */
void MenuWindow::onCloseWindow(wxCloseEvent& event)
{
    wxWindowList list = this->GetChildren();
    
    int count = 0;
    
    // zjistíme si počet podřízených oken (objekty třídy wxFrame)
    wxWindowListNode *node = list.GetFirst();
    while (node)
    {
      wxWindow *win = node->GetData();
      
      if (win->IsKindOf(CLASSINFO(wxFrame)))
      {
          count++;
      }
      node = node->GetNext();
    }

    
    // pokud existuje nějaké podřízené okno, zeptáme se uživatele, zda opravdu
    // chce ukončit program
    if (count > 0)
    {
        wxMessageDialog* dialog = new wxMessageDialog(this,
              wxT("Opravdu chcete ukončit hru?"), wxT("Dáma 2008"), wxYES|wxNO);
        int answer = dialog->ShowModal();
        dialog->Destroy();
        
        if (answer == wxID_NO)
        {
            return;
        }
    }
    
    // zničíme okno
    this->Destroy();
}

// wxGlade: add MenuWindow event handlers


void MenuWindow::set_properties()
{
    // begin wxGlade: MenuWindow::set_properties
    SetTitle(_("Dáma 2008"));
    buttonLogin->SetFocus();
    // end wxGlade
}


void MenuWindow::do_layout()
{
    // begin wxGlade: MenuWindow::do_layout
    wxBoxSizer* sizer_3 = new wxBoxSizer(wxVERTICAL);
    wxBoxSizer* sizer_3_copy = new wxBoxSizer(wxVERTICAL);
    sizer_3_copy->Add(bitmapLogo, 0, wxBOTTOM|wxALIGN_CENTER_HORIZONTAL, 10);
    sizer_3_copy->Add(buttonLogin, 0, wxEXPAND|wxALIGN_CENTER_HORIZONTAL, 0);
    sizer_3_copy->Add(buttonLocal, 0, wxEXPAND|wxALIGN_CENTER_HORIZONTAL, 0);
    sizer_3_copy->Add(buttonReplay, 0, wxEXPAND|wxALIGN_CENTER_HORIZONTAL, 0);
    sizer_3_copy->Add(buttonHelp, 0, wxEXPAND|wxALIGN_CENTER_HORIZONTAL, 0);
    sizer_3_copy->Add(buttonAbout, 0, wxEXPAND|wxALIGN_CENTER_HORIZONTAL, 0);
    sizer_3_copy->Add(buttonQuit, 0, wxEXPAND|wxALIGN_CENTER_HORIZONTAL, 0);
    sizer_3->Add(sizer_3_copy, 1, wxALL|wxEXPAND, 10);
    SetSizer(sizer_3);
    sizer_3->Fit(this);
    sizer_3->SetSizeHints(this);
    Layout();
    Centre();
    // end wxGlade
}

/**
 * Povolí tlačítko pro přihlášení
 */
void MenuWindow::enableLogin()
{
    buttonLogin->Enable(true);
}

/**
 * Zakáže tlačítko pro přihlášení
 */
void MenuWindow::disableLogin()
{
    buttonLogin->Enable(false);
}

